name: Upload Software to TIRA
on: workflow_dispatch
jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Set up QEMU for cross-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Step 5: Install required Python packages
      - name: Install required Python packages
        run: |
          python -m pip install --upgrade pip
          pip install tira

      # Step 6: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t registry.webis.de/code-research/tira/tira-user-ir-wise-24-infobees/github-action-submission:0.0.1 -f ./Dockerfile .

      # Step 7: Push and execute with TIRA
      - name: Run TIRA Command
        env:
          TIRA_CLIENT_TOKEN: ${{ secrets.TIRA_CLIENT_TOKEN }}
        run: |
          tira-run \
            --tira-client-token "${TIRA_CLIENT_TOKEN}" \
            --input-dataset ir-lab-wise-2024/subsampled-ms-marco-deep-learning-20241201-training \
            --image registry.webis.de/code-research/tira/tira-user-ir-wise-24-infobees/github-action-submission:0.0.1 \
            --push true \
            --fail-if-output-is-empty
