name: Upload Software to TIRA
on: workflow_dispatch
jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up QEMU for cross-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Set up Python environment
      - name: Set up Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Install required Python packages
      - name: Install Required Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install tira

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t registry.webis.de/code-research/tira/tira-user-ir-wise-24-infobees/github-action-submission:0.0.1 -f ./Dockerfile .

      # Debug Docker image build
      - name: List Docker Images
        run: docker images

      # Run TIRA command to upload and push the image
      - name: Test and Push Image to TIRA
        env:
          TIRA_CLIENT_TOKEN: ${{ secrets.TIRA_CLIENT_TOKEN }}
        run: |
          tira-run \
            --tira-client-token "${TIRA_CLIENT_TOKEN}" \
            --input-dataset ir-lab-wise-2024/subsampled-ms-marco-deep-learning-20241201-training \
            --image registry.webis.de/code-research/tira/tira-user-ir-wise-24-infobees/github-action-submission:0.0.1 \
            --push true \
            --fail-if-output-is-empty
