name: Upload Software to TIRA1
on: workflow_dispatch
jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install required Python packages
        run: |
          python -m pip install --upgrade pip
          pip install tira

      - name: Build Docker Image
        run: |
          docker build -t registry.webis.de/code-research/tira/tira-user-ir-wise-24-infobees/github-action-submission:0.0.1 -f ./Dockerfile .

      - name: Run TIRA Command
        env:
          TIRA_CLIENT_TOKEN: ${{ secrets.TIRA_CLIENT_TOKEN }}
        run: |
          tira-run \
            --tira-client-token "${TIRA_CLIENT_TOKEN}" \
            --tira-vm-id "ir-wise-24-infobees-vm" \
            --input-dataset "ir-lab-wise-2024/subsampled-ms-marco-deep-learning-20241201-training" \
            --image registry.webis.de/code-research/tira/tira-user-ir-wise-24-infobees/github-action-submission:0.0.1 \
            --command "-i ir-lab-wise-2024/subsampled-ms-marco-deep-learning-20241201-training -o /output" \
            --push true \
            --fail-if-output-is-empty

